OPTIM?=1
TRACING?=0
DYNSTACK?=0
OLDURING?=0

CFGFLAGS=-pthread -fPIC -Wall -Wextra
DBGFLAGS=-ggdb # -fsanitize=address
LANGFLAGS=-std=c++11

CFLAGS=$(CFGFLAGS) $(DBGFLAGS) $(OPTFLAGS) $(STACKFLAGS) $(TLSFLAGS)
CXXFLAGS=$(CFLAGS) $(LANGFLAGS)

ifeq ($(OPTIM),1)
OPTFLAGS=-O3 -fno-omit-frame-pointer
endif

ifeq ($(TRACING),1)
LTTNG:=$(shell lttng-gen-tp --help 2>/dev/null)
ifdef LTTNG
CFLAGS+=-DTRACING
else
TRACING=0
endif
endif

ifeq ($(OLDURING),1)
CFLAGS+=-DOLDURING
endif

ifeq ($(DYNSTACK),1)
STACKFLAGS=-fsplit-stack -DSPLIT_STACK
else
#STACKFLAGS=-Wstack-usage=4096
endif

# this test works for clang invoked as 'cc' on FreeBSD
ifeq ($(shell $(CC) --version|head -1|grep -F -q clang),0)
TLSFLAGS=-fno-extern-tls-init -mtls-dialect=gnu2
endif

ifeq ($(CC),clang)
CXX=clang++
endif
